source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'AusomeParking' do
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

# when not using frameworks  we can do this instead of including the source files in our project (1/4):
# pod 'react-native-maps', path: '../../'
#	pod 'react-native-google-maps', path: '../../'  # <~~ if you need GoogleMaps support on iOS

# when not using frameworks  we can remove this line (2/4):
  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
end